language: java
matrix:
    include:
        - os: linux
          jdk: oraclejdk8
        - os: linux
          jdk: openjdk8
        - os: osx
          osx_image: xcode9.1
    allow_failures:
        - os: osx
branches:
 only:
   - master
notifications:
 email:
  - support@openam.org.ru
before_install:
 - date -u
 - uname -a
 - env | sort
 - mvn -q -B -DskipTests clean install -f OpenDJ/forgerock-parent
 - mvn -q -B -DskipTests clean install -f OpenDJ
script:
 - mvn -q -B clean install
